```{r}
library(nflreadr)
library(cmdstanr)
library(tidyverse)
set.seed(1998)

file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

load_pbp(2021) -> pbp

pbp |> 
  select(air_yards, qb_hit) |> 
  filter(air_yards >= 0) -> pbp2

kappa = 0.8
delta = 0.3
random = runif(1000, 0, 1)
alpha = 7
beta = -5

sim_data <- tibble(qb_hit = rbinom(n=1000,size=1,prob=kappa), air_yards = rpois(n = 1000, lambda = alpha + beta * qb_hit))

data_list <- list('notes' = sim_data$air_yards,'cat' = sim_data$qb_hit, "N" = 1000)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit)

#model works
```

```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy2.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

sim_data2 <- tibble(qb_hit = rbinom(n=1000,size=1,prob=kappa), id = rep(1:5, times = 200), air_yards = rpois(n = 1000, lambda = alpha + id + beta * qb_hit))

data_list <- list('notes' = sim_data2$air_yards,'cat' = sim_data2$qb_hit, "N" = 1000, "N_id" = 5, "id" = sim_data2$id)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit, depth = 2)

#seems to work
```

```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy3.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))


sim_data3 <- tibble(qb_hit = rbinom(n=1000,size=1,prob=kappa), id = rep(1:5, times = 200), air_yards = rpois(n = 1000, lambda = alpha + beta * qb_hit)) |>  
  mutate(qb_hit_observed = ifelse(qb_hit == 1 & delta > random, 0, qb_hit))

data_list <- list('notes' = sim_data3$air_yards,'cat' = sim_data3$qb_hit_observed, "N" = 1000)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit)

#seems to work
```


```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy5.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))
random <- runif(1000,0,1)

sim_data4 <- tibble(qb_hit = rbinom(n=1000,size=1,prob=kappa), id = rep(1:5, times = 200), air_yards = rpois(n = 1000, lambda = alpha + id + beta * qb_hit)) |>  
  mutate(qb_hit_observed = ifelse(qb_hit == 1 & delta > random, 0, qb_hit))

data_list <- list('notes' = sim_data4$air_yards,'cat' = sim_data4$qb_hit_observed, "N" = 1000, "id" = sim_data4$id, "N_id" = 5 )

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit, depth = 2)
```

###########################################################

We are now past the proof of concept phase

###########################################################

```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

load_pbp(2021) -> pbp

pbp |> 
  select(air_yards, qb_hit) |> 
  filter(air_yards >= 0) |> 
  slice_sample(n = 1000)-> pbp2

data_list <- list('notes' = pbp2$air_yards,'cat' = pbp2$qb_hit, "N" = 1000)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit)
```

```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy2.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

pbp |> 
  filter(!is.na(posteam)) |> 
  distinct(posteam) |> 
  mutate(id = row_number()) -> teams

pbp |> 
  select(air_yards, qb_hit, posteam) |> 
  filter(air_yards >= 0) |> 
  slice_sample(n = 1000) |> 
  left_join(teams)-> pbp2

data_list <- list('notes' = pbp2$air_yards,'cat' = pbp2$qb_hit, "N" = 1000, "N_id" = 32, "id" = pbp2$id)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit, depth = 2)

rethinking::precis(fit, depth = 2) |>  as_tibble() |> slice_head(n = 64) |>  mutate(id = rep(1:32, times = 2), name = c(rep("alpha", times = 32), rep("beta", times = 32))) |> left_join(teams) -> predicted_values

predicted_values |> 
  select(posteam, name, mean, sd) |> 
  pivot_wider(names_from = name, values_from = c(mean, sd)) -> predicted_values2
```

```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy3.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

pbp |> 
  select(air_yards, qb_hit) |> 
  filter(air_yards >= 0) |> 
  slice_sample(n = 1000) |> 
  rename(qb_hit_observed = qb_hit)-> pbp2

data_list <- list('notes' = pbp2$air_yards,'cat' = pbp2$qb_hit_observed, "N" = 1000)

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  refresh = 500 # print update every 500 iters
)

rethinking::precis(fit)
```


```{r}
file <- file.path("/home/jonastrostle/Downloads/occupancy", "cats-occupancy4.stan")
mod <- cmdstan_model(file, stanc_options = list("O1"))

pbp |> 
  filter(!is.na(posteam)) |> 
  distinct(posteam) |> 
  mutate(id = row_number()) -> teams

pbp |> 
  select(air_yards, qb_hit, posteam) |> 
  filter(air_yards >= 0) |> 
  slice_sample(n = 1000) |> 
  left_join(teams) |> 
  rename(qb_hit_observed = qb_hit) -> pbp2

data_list <- list('notes' = pbp2$air_yards,'cat' = pbp2$qb_hit_observed, "N" = 1000, "id" = pbp2$id, "N_id" = 32 )

fit <- mod$sample(
  data = data_list, 
  seed = 123, 
  chains = 4, 
  parallel_chains = 4,
  iter_sampling = 3000,
  refresh = 100 # print update every 500 iters
)

rethinking::precis(fit, depth = 2)

|>  as_tibble() |> filter(mean != 0.50) |> slice_head(n = 128) |>  mutate(id = rep(1:32, times = 4), name = c(rep("kappa", times = 32), rep("delta", times = 32), rep("alpha", times = 32), rep("beta", times = 32))) |> left_join(teams) -> predicted_values3

predicted_values3 |> 
  select(posteam, name, mean, sd, rhat) |> 
  pivot_wider(names_from = name, values_from = c(mean, sd, rhat)) -> predicted_values4
```

```{r}
hist(pbp2$air_yards)
hist(sim_data4$air_yards)
```

